name: Build Linux
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: jurplel/install-qt-action@b3ea5275e37b734d027040e2c7fe7a10ea2ef946
        with:
          cache: true
      - name: cache linuxdeployqt
        id: cache-appimage
        uses: actions/cache@v3
        with:
          path: linuxdeployqt-continuous-x86_64.AppImage
          key: linuxdeployqt-x86_64
      - if: ${{ steps.cache-appimage.outputs.cache-hit != 'true' }}
        name: download linuxdeployqt
        run: |
          curl -LO https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
      - name: install linuxdeployqt
        run: |
          chmod +x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
          sudo cp -pr squashfs-root/usr/bin/* /usr/bin/
          sudo cp -pr squashfs-root/usr/lib/* /usr/lib/
          rm -rf squashfs-root
          chmod -x linuxdeployqt-continuous-x86_64.AppImage
      - name: build
        run: |
          make build-linux
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: minikube-gui-linux
          path: ./minikube-gui-linux.AppImage
